### ISSUE TITLE
Fix Clang build for Travis-CI

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri#277]
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

The clang build 100% successful on Arch, Ubuntu 15.10, and OSX but it [doesn't like cpp-netlib on 14.04](https://travis-ci.org/monero-project/kovri/jobs/148151371). This could be an upstream issue but more info is needed before jumping to conclusions (note: a simple ```-stdlib=libc++``` is useless). The gcc build is 100% successful on a Linux's, so this issue is minor.

Excerpt from the [Travis build](https://travis-ci.org/monero-project/kovri/jobs/148151371):

```
/usr/bin/ld: CMakeFiles/cpp-netlib-http-server_async_run_stop_concurrency.dir/server_async_run_stop_concurrency.cpp.o: undefined reference to symbol '_ZNKSs5emptyEv@@GLIBCXX_3.4'
//usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
```

**Comment by anonimal** [comment]
Referencing https://github.com/cpp-netlib/cpp-netlib/issues/674

**Comment by anonimal** [comment]
As noted elsewhere, the 14.04 clang build is successful on internal VMs (one being a fresh image) but is unsuccessful on Travis CI.

**Comment by anonimal** [comment]
The build issue is purely with Travis and an issue has [been opened]( https://github.com/travis-ci/travis-ci/issues/6384). We can build successfully on Ubuntu Trusty 14.04 with the same build process and package dependencies.

**Comment by rakhimov** [comment]
I am on Ubuntu 16.04 with Clang 3.8. It used to fail to link with GCC 5 ABI.
I believe the ABI has been fixed recently. I am currently getting it to link successfully.
https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.8/+bug/1510042

**Comment by anonimal** [comment]
This issue was specific to Travis. I haven't been able to reproduce the problems with 3.6.2 on 14.04. We've been able to build fine with 3.6.2 on Wily and Xenial and I haven't had problems with 3.8 on Arch either. Can you give more details about the linkage error?

We *could* make 3.8 the default minimum requirement since we're using ```llvm-toolchain-trusty``` anyway. I'm also not attached to 3.6.2 but I also don't see the need to enforce upgrades for a Travis CI issue.

I'm curious to see the Travis build with 3.8 so, feel free to PR.

**Comment by rakhimov** [comment]
I got clang 3.5 working here: https://travis-ci.org/rakhimov/kovri/builds/149550694
You need to install GCC 4.9 instead of GCC 5 alongside clang to support C++14.

I don't see a compelling reason to increase the minimal requirement for clang.
clang 3.4 has a full support for c++14.

**Comment by anonimal** [comment]
@rakhimov https://github.com/cpp-netlib/cpp-netlib/issues/674

If you can build on gcc 4.9 alongside clang 3.5 on both Travis (multi-compiler option) and your own VMs of Trusty and Xenial, then feel free to send a PR making any Travis adjustments and updating docs where appropriate. I don't have time to do everything.

**Comment by rakhimov** [comment]
Does kovri really need GCC 5?
The only major thing GCC 5 gives is extended constexpr. I doubt kovri is using them.

**Comment by anonimal** [comment]
The last I checked, 4.8.2 is unusable. I had never tested with the 4.9 because I was regularly developing on platforms where 5 or higher were default so, when pulling from ```ubuntu-toolchain-r-test```, it was easier to pull in 5 for consistency rather than dealing with a backported 4.9.

More eyes = more flexibility and fine tuning, so thanks for the PR and news of the ABI update.
