### ISSUE TITLE
Kovri doesn't build with Boost 1.67

### ISSUE THREAD

**Issue by btolfa** [monero-project/kovri#855]
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

Compilers throw the following errors:

MSVC
```
kovri\src\client\address_book\impl.cc(92): error C2440: '<function-style-cast>': cannot convert from 'kovri::client::AddressBookDefaults::SubscriberTimeout' to 'boost::posix_time::minutes'
kovri\src\client\address_book\impl.cc(94): note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

clang
```
kovri\src\client\address_book\impl.cc(92): error: no matching conversion for functional-style cast from 'kovri::client::AddressBookDefaults' to 'boost::posix_time::minutes'
```

gcc
```
kovri\src\client\address_book\impl.cc(92): error: no matching function for call to 'boost::posix_time::minutes::minutes(kovri::client::AddressBookDefaults::SubscriberTimeout)'
```

**Comment by coneiric** [comment]
@btolfa Kovri builds against Boost 1.58, since this is required for Ubuntu x86_64. This can be seen in the failing buildbot check in #856. I'm unaware if there are plans to change the Boost minimal/target version, but I don't believe there are.

**Comment by btolfa** [comment]
@coneiric The failure of [buildbot/kovri-all-ubuntu-amd64](https://build.getmonero.org/builders/kovri-all-ubuntu-amd64/builds/956) isn't caused by this changes or boost.
```
Assembler messages:
Fatal error: can't create CMakeFiles/kovri-util.dir/cpuid.cc.o: No such file or directory
src/util/CMakeFiles/kovri-util.dir/build.make:254: recipe for target 'src/util/CMakeFiles/kovri-util.dir/cpuid.cc.o' failed
```

Something is wrong with that buildbot.
Other builds which use boost 1.58 are green - [buildbot/kovri-all-ubuntu-i686](https://build.getmonero.org/builders/kovri-all-ubuntu-i686/builds/899)

**Comment by coneiric** [comment]
@btolfa Sorry about that, also just saw your conversation in another issue about custom FindBoost.cmake for Windows.
